Webkul\UVDesk\CoreBundle\Entity\SavedFilters:
    type: entity
    table: uv_saved_filters
    manyToOne:
        user:
            targetEntity: UserInstance
            inversedBy: userSavedFilters
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: true
                onDelete: cascade
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 191
        filtering:
            type: json_array
            nullable: true
        route:
            type: string
            length: 191
            nullable: true
        dateAdded:
            type: datetime
            column: date_added
        dateUpdated:
            type: datetime
            column: date_updated
    lifecycleCallbacks: {  }
