Webkul\UVDesk\CoreBundle\Entity\SupportRole:
    type: entity
    table: uv_support_role
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 191
            unique: true
        description:
            type: string
            length: 191
            nullable: true
    lifecycleCallbacks: {  }
