Webkul\UVDesk\CoreBundle\Entity\SupportPrivilege:
    type: entity
    table: uv_support_privilege
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\SupportPrivilegeRepository
    manyToMany:
        users:
            targetEntity: UserInstance
            mappedBy: supportPrivileges
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 191
        description:
            type: text
        privileges:
            type: array
            nullable: true
        createdAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ initializeTimestamp ]
