Webkul\UVDesk\CoreBundle\Entity\Thread:
    type: entity
    table: uv_thread
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\ThreadRepository
    oneToMany:
        attachments:
            targetEntity: Attachment
            mappedBy: thread
            cascade: [remove]
            orphanRemoval: true
    manyToOne:
        ticket:
            targetEntity: Ticket
            inversedBy: threads
            joinColumn:
                name: ticket_id
                referencedColumnName: id
                onDelete: CASCADE
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: SET NULL
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        source:
            type: string
            length: 191
        messageId:
            type: text
            nullable: true
        threadType:
            type: string
            length: 191
        createdBy:
            type: string
            length: 191
        cc:
            type: array
            nullable: true
        bcc:
            type: array
            nullable: true
        replyTo:
            type: array
            nullable: true
        deliveryStatus:
            type: string
            length: 255
            nullable: true
        isLocked:
            type: boolean
            options:
                default: false
        isBookmarked:
            type: boolean
            options:
                default: false
        message:
            type: text
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        agentViewedAt:
            type: datetime
            nullable: true
        customerViewedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
