Webkul\UVDesk\CoreBundle\Entity\User:
    type: entity
    table: uv_user
    repositoryClass: Webkul\UVDesk\CoreBundle\Repository\UserRepository
    oneToMany:
        userInstance:
            targetEntity: UserInstance
            mappedBy: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 191
            unique: true
            nullable: true
        proxyId:
            type: string
            length: 191
            nullable: true
            unique: true
        password:
            type: string
            length: 191
            nullable: true
        firstName:
            type: string
            length: 191
        lastName:
            type: string
            length: 191
            nullable: true
        isEnabled:
            type: boolean
            default: false
        verificationCode:
            type: string
            length: 191
            nullable: true
            unique: true
        timezone:
            type: string
            length: '191'
            nullable: true
        timeformat:
            type: string
            length: '191'
            nullable: true
    lifecycleCallbacks: {  }
